# Generated by Django 6.0.5 on 2026-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada de Mercadería'), ('SALIDA', 'Salida (Despacho)'), ('TRASLADO', 'Traslado (Bodega a Vitrina)'), ('AVERIA', 'Ajuste por Merma/Daño'), ('CORRECCION', 'Ajuste Administrativo')], max_length=15)),
                ('cantidad', models.PositiveIntegerField()),
                ('origen', models.CharField(choices=[('BODEGA', 'Bodega'), ('VITRINA', 'Vitrina'), ('EXTERNO', 'Proveedor/Cliente Externo')], max_length=10)),
                ('destino', models.CharField(choices=[('BODEGA', 'Bodega'), ('VITRINA', 'Vitrina'), ('EXTERNO', 'Proveedor/Cliente Externo')], max_length=10)),
                ('justificacion', models.TextField(blank=True, help_text='Obligatorio para justificar mermas o correcciones administrativas.', null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos_inventario',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock_bodega', models.PositiveIntegerField(default=0)),
                ('stock_vitrina', models.PositiveIntegerField(default=0)),
                ('stock_minimo', models.PositiveIntegerField(default=1, help_text='Cantidad mínima permitida antes de disparar alertas (Mayor a cero).')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
