# Generated by Django 6.0.5 on 2026-05-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DestinatarioCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(help_text='Correo electrónico que recibirá las alertas de stock crítico.', max_length=254, unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Permite activar o desactivar el envío global a este correo.')),
            ],
            options={
                'db_table': 'destinatarios_correo',
            },
        ),
        migrations.CreateModel(
            name='HistorialAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_momento', models.PositiveIntegerField(help_text='Stock total que tenía el artículo al momento de activarse la alerta.')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora exacta del disparo de la alerta.')),
                ('notificacion_enviada', models.BooleanField(default=False, help_text='Indica si el correo electrónico se envió con éxito.')),
            ],
            options={
                'db_table': 'historial_alertas',
                'ordering': ['-fecha_hora'],
                'get_latest_by': 'fecha_hora',
            },
        ),
    ]
