"""
Django settings for libreria_papelitos project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-y*7-@3)w*f&t%ny+gt-ran4tjm#9te(fpw3u$un@7=g@j7$%up'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # --- LIBRERÍAS DE TERCEROS (Ecosistema API REST) ---
    'rest_framework', #Framework principal para construir los Endpoints y Serializadores
    'rest_framework.authtoken', # Sistema nativo de Django REST para autenticación basada en tokens de seguridad
    'corsheaders', # Middleware encargado de mitigar restricciones de origen cruzado (CORS)

    # --- MÓDULOS PROPIOS DEL SISTEMA (Librería Papelitos) ---
    'inventario', # Manejo de productos, categorías y transacciones de stock
    'seguridad', # Manejo de autenticación y autorización de usuarios
    'alertas', # Sistema de notificaciones y alertas
    'reportes', # Generación de reportes y estadísticas
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Habilitado arriba en la lista para interceptar peticiones CORS antes de procesar rutas
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'libreria_papelitos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'libreria_papelitos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', # Base de datos local ligera para el entorno de desarrollo actual
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#--- MODELO DE USUARIO PERSONALIZADO ---
# Redirige el sistema de autenticación nativo de Django para que use nuestra clase Usuario
# definida dentro de la app seguridad, permitiendo extender campos personalizados (roles, etc.)
AUTH_USER_MODEL = 'seguridad.Usuario'

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Permitir peticiones desde el servidor de desarrollo de Vite (Frontend)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    # Define TokenAuthentication como mecanismo global para validar las credenciales de los usuarios en cada endpoint
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    # Permite el acceso abierto de manera predeterminada; las restricciones específicas por rol o sesión
    # se aplican directamente en las vistas mediante permission_classes = [IsAuthenticated] o permisos personalizados según el caso
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}