# Generated by Django 6.0.5 on 2026-05-30 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(choices=[('GER', 'Gerencia'), ('BOD', 'Bodega'), ('VIT', 'Vitrina')], default='BOD', max_length=3),
        ),
    ]
