# Generated by Django 6.0.5 on 2026-05-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('BODEGA', 'Operador de Bodega'), ('CAJA', 'Operador de Caja')], default='BODEGA', help_text='Rol asignado para el control de accesos y restricción de vistas.', max_length=10),
        ),
    ]
