# Generated by Django 6.0.5 on 2026-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_usuario_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ej: LISTADO_ARTICULOS', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Ej: Listado de Artículos', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modulos_sistema',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='modulos_permitidos',
            field=models.ManyToManyField(blank=True, to='seguridad.modulosistema'),
        ),
    ]
