# Generated by Django 6.0.5 on 2026-05-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0003_modulosistema_usuario_modulos_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='configuracion_accesos',
            field=models.JSONField(blank=True, default=dict, help_text='Almacena los permisos granulares (agregar, editar, etc) en formato JSON', null=True),
        ),
    ]
