# Generated by Django 6.0.5 on 2026-05-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0004_usuario_configuracion_accesos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='modulos_permitidos',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='configuracion_accesos',
        ),
        migrations.DeleteModel(
            name='ModuloSistema',
        ),
    ]
