# Generated by Django 6.0.5 on 2026-05-30 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0005_remove_usuario_modulos_permitidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='configuracion_accesos',
            field=models.JSONField(blank=True, default=dict, help_text='Guarda los permisos de React (master, agregar, editar, etc)', null=True),
        ),
    ]
