# Generated by Django 6.0.5 on 2026-05-31 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0002_alter_usuario_rol'),
        ('seguridad', '0006_usuario_configuracion_accesos'),
    ]

    operations = [
    ]
