# Generated by Django 6.0.5 on 2026-09-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0007_merge_20260531_0746'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=150)),
                ('evento', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bitacora_seguridad',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
